services:
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "0.0.0.0:1337:1337"
    env_file: ./strapi/.env
    environment:
      - STRAPI_URL=http://178.105.144.65:1337
    volumes:
      - strapi_uploads:/app/public/uploads
      - strapi_data:/app/.tmp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_STRAPI_URL=http://178.105.144.65:1337
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - STRAPI_URL=http://strapi:1337
      - NEXT_PUBLIC_STRAPI_URL=http://178.105.144.65:1337
    depends_on:
      - strapi

volumes:
  strapi_uploads:
  strapi_data:
